### PR TITLE
Fix: wrong input values used when creating a base image

### LINKED ISSUE #574: Align Base Image creation page with new GraphQL Schema
The Base Image creation page is still using the old localized fields, preventing a Base Image creation since the backend returns an error.
It should switch to using `localizedDescriptions` and `localizedReleaseDisplayNames`.

### PR DESCRIPTION
**Pull request by davidebriani**
Some input fields were not updated during the migration to the newest version of the GraphQL API.
This change fixes how localized fields are provided in the mutation when creating a base image.

Fixes #574

### CODE REVIEW

File: frontend/src/forms/CreateBaseImage.tsx [hunk 1]
```diff
@@ -129,20 +129,31 @@ const transformOutputData = (
...
-    text: data.description,
-  },
-});
+): BaseImageData => {
+  const baseImage: BaseImageData = {
+    baseImageCollectionId: baseImageCollection.id,
+    file: data.file[0],
+    version: data.version,
+    startingVersionRequirement: data.startingVersionRequirement,
+    localizedReleaseDisplayNames: [
```
Comment (rbino) [inline frontend/src/forms/CreateBaseImage.tsx:138]: If I understand the logic below, this should be behind an `if` too because it's optional

Comment (davidebriani) [reply frontend/src/forms/CreateBaseImage.tsx]: Makes sense, fixed it.
